[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
ticket_fields = { path = "../../../helpers/ticket_fields" }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8.*" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
